runtime: nodejs
service: frontend

handlers:
# Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
# env: flex
# runtime_config:
#  operating_system: ubuntu22
#  runtime_version: "18.12.1"
# manual_scaling:
#  instances: 1
# resources:
#  cpu: 4
 # memory_gb: 16
#  disk_size_gb: 30

